# cloudbuild.yaml
steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      "build",
      "-t",
      "us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1",
      "."
    ]

# Deploy to Cloud Run with secrets
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      "run","deploy","fantasy-basketball-assistant",
      "--image","us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1",
      "--region","us-west2",
      "--platform","managed",
      "--allow-unauthenticated",
      "--update-secrets","/secrets/firebase.json=firebase-credentials:latest",
      "--set-env-vars","FIREBASE_CREDENTIALS=/secrets/firebase.json",
      "--update-secrets","API_KEY=API_KEY_SECRET:latest"
    ]

images:
- us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1

options:
  logging: CLOUD_LOGGING_ONLY